name: SGI
channels:
  - conda-forge
  - defaults
dependencies:
  - aom=3.6.0
  - asttokens=3.0.0
  - attrs=25.4.0
  - beautifulsoup4=4.13.5
  - blas=1.0
  - blosc=1.21.6
  - bottleneck=1.4.2
  - branca=0.8.1
  - brotli-python=1.0.9
  - brotlicffi=1.1.0.0
  - bs4=4.13.5
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - cairo=1.18.4
  - cartogram=1.0.0
  - catalogue=2.0.10
  - cffi=2.0.0
  - click=8.2.1
  - cloudpathlib=0.21.0
  - cloudpickle=3.1.1
  - colorama=0.4.6
  - comm=0.2.3
  - confection=0.1.5
  - contourpy=1.3.1
  - cpython=3.11.13
  - cycler=0.11.0
  - cymem=2.0.11
  - cython-blis=1.0.1
  - dav1d=1.2.1
  - debugpy=1.8.16
  - decorator=5.2.1
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - expat=2.7.1
  - folium=0.20.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.1
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - fonttools=4.55.3
  - freeglut=3.4.0
  - freetype=2.13.3
  - freexl=2.0.0
  - fribidi=1.0.10
  - geodatasets=2024.8.0
  - geopandas=1.1.1
  - geopandas-base=1.1.1
  - geos=3.10.6
  - geotiff=1.7.0
  - getopt-win32=0.1
  - giflib=5.2.2
  - glib=2.84.2
  - glib-tools=2.84.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - graphite2=1.3.14
  - graphviz=2.50.0
  - gts=0.7.6
  - harfbuzz=10.2.0
  - icc_rt=2022.1.0
  - icu=73.1
  - importlib-metadata=8.7.0
  - intel-openmp=2025.0.0
  - ipykernel=6.30.1
  - ipython=9.5.0
  - ipython_pygments_lexers=1.1.1
  - ipywidgets=8.1.8
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.2
  - jpeg=9e
  - jsonschema=4.25.1
  - jsonschema-specifications=2025.9.1
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - jupyterlab_widgets=3.0.16
  - kiwisolver=1.4.8
  - krb5=1.21.3
  - langcodes=3.5.0
  - language-data=1.3.0
  - lcms2=2.16
  - lerc=4.0.0
  - libarchive=3.7.7
  - libavif=1.1.1
  - libboost=1.88.0
  - libcurl=8.15.0
  - libdeflate=1.22
  - libffi=3.4.4
  - libgd=2.3.3
  - libgdal-core=3.11.0
  - libglib=2.84.2
  - libiconv=1.16
  - libkml=1.3.0
  - libkrb5=1.21.3
  - libpng=1.6.39
  - libpq=17.4
  - libsodium=1.0.20
  - libspatialite=5.1.0
  - libssh2=1.11.1
  - libtiff=4.7.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxml2=2.13.8
  - lz4-c=1.9.4
  - mapclassify=2.10.0
  - marisa-trie=1.3.1
  - markdown-it-py=4.0.0
  - matplotlib=3.10.5
  - matplotlib-base=3.10.5
  - matplotlib-inline=0.1.7
  - mdurl=0.1.2
  - minizip=4.0.3
  - mkl=2025.0.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - murmurhash=1.0.15
  - narwhals=2.7.0
  - nbformat=5.10.4
  - nest-asyncio=1.6.0
  - networkx=3.5
  - nltk=3.9.2
  - numexpr=2.11.0
  - numpy=2.3.5
  - numpy-base=2.3.5
  - openjpeg=2.5.2
  - openssl=3.6.0
  - packaging=25.0
  - pandas=2.3.3
  - pango=1.50.7
  - parso=0.8.5
  - pcre2=10.42
  - pickleshare=0.7.5
  - pillow=11.3.0
  - pip=25.2
  - pixman=0.46.4
  - platformdirs=4.4.0
  - plotly=6.4.0
  - pooch=1.8.2
  - poppler=24.09.0
  - poppler-data=0.4.11
  - preshed=3.0.9
  - proj=9.3.1
  - prompt-toolkit=3.0.52
  - psutil=7.0.0
  - pure_eval=0.2.3
  - pycparser=2.23
  - pydot=3.0.4
  - pygments=2.19.2
  - pygraphviz=1.14
  - pyogrio=0.10.0
  - pyparsing=3.2.0
  - pyproj=3.6.1
  - pyqt=6.7.1
  - pyqt6-sip=13.9.1
  - pysocks=1.7.1
  - python=3.11.13
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.2
  - python-tzdata=2025.2
  - python_abi=3.11
  - pytz=2025.2
  - pywin32=311
  - pyzmq=27.0.2
  - qtbase=6.7.3
  - qtdeclarative=6.7.3
  - qtsvg=6.7.3
  - qttools=6.7.3
  - qtwebchannel=6.7.3
  - qtwebsockets=6.7.3
  - referencing=0.37.0
  - regex=2025.9.1
  - requests=2.32.5
  - rich=13.9.4
  - rpds-py=0.28.0
  - ruamel_yaml=0.17.21
  - scipy=1.16.0
  - seaborn=0.13.2
  - setuptools=78.1.1
  - shapely=2.1.1
  - shellingham=1.5.4
  - sip=6.10.0
  - six=1.17.0
  - smart_open=7.3.1
  - soupsieve=2.5
  - spacy=3.8.2
  - spacy-legacy=3.0.12
  - spacy-loggers=1.0.4
  - spacy-model-en_core_web_sm=3.8.0
  - sqlite=3.50.2
  - srsly=2.5.2
  - stack_data=0.6.3
  - sympy=1.14.0
  - tbb=2022.0.0
  - tbb-devel=2022.0.0
  - thinc=8.3.2
  - tk=8.6.15
  - tornado=6.5.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typer=0.9.0
  - typing-extensions=4.15.0
  - typing-inspection=0.4.2
  - typing_extensions=4.15.0
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - ujson=5.11.0
  - unicodedata2=15.1.0
  - uriparser=0.9.8
  - urllib3=2.5.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wasabi=1.1.3
  - wcwidth=0.2.13
  - weasel=0.4.1
  - wheel=0.45.1
  - widgetsnbextension=4.0.15
  - win_inet_pton=1.1.0
  - wordcloud=1.9.4
  - wrapt=2.0.1
  - xerces-c=3.2.4
  - xyzservices=2025.4.0
  - xz=5.6.4
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - annotated-types==0.7.0
      - anyio==4.11.0
      - certifi==2025.8.3
      - charset-normalizer==3.4.3
      - distro==1.9.0
      - filelock==3.20.0
      - fsspec==2025.10.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - idna==3.10
      - jiter==0.11.1
      - markupsafe==3.0.3
      - newsdataapi==0.1.28
      - openai==2.7.1
      - powerlaw==1.5
      - pydantic==2.12.3
      - pydantic-core==2.41.4
      - pyyaml==6.0.3
      - safetensors==0.6.2
      - scikit-learn==1.7.2
      - sentence-transformers==5.1.2
      - sniffio==1.3.1
      - threadpoolctl==3.6.0
      - tokenizers==0.22.1
      - torch==2.9.0
      - transformers==4.57.1
prefix: C:\Users\willi\anaconda3\envs\SGI
